### PR TITLE
em/japan

### PR DESCRIPTION
**Pull request by lotusfleur01**
This is the initial branch on my portion of the project.

I have added my country specific data and image.

Please verify that you see the image and the date that I entered re; Japan.

### CODE REVIEW

**Review by kristen-howton — CHANGES_REQUESTED** [review]
Please pull down the changes from master. Let me know if you need assistance.

**Comment by lotusfleur01** [comment]
Hey

I believe I have made my changes you requested please re - review my work.

**Comment by lotusfleur01** [comment]
Hey 

I made the new "new" changes and believe this is now correct. Please review.

**Review by kristen-howton — APPROVED** [review]
👍 Looks awesome Erika!! Please merge to master!! :)

**Pull request merged**
